### ISSUE TITLE
How do you perform decoding after encoding?

### ISSUE THREAD

**Issue by swiss-vault** [randombit/fecpp#19]
Is the decoding part of the program available? Is it the test_recovery binary that does the decoding? I tried running `./test_recovery --help` but it didn't provide any help. Thank you.

**Comment by randombit** [comment]
Bad news: This library is no longer maintained.

Good news: The same functionality (zfec-compatible forward error correction with SIMD optimizations) is available in Botan with randombit/botan#2866

There is some examples of decoding in the new tests in that PR
