### ISSUE TITLE
ld: library not found for -lboost_python on MacOS

### ISSUE THREAD

**Issue by cnshicongming** [randombit/fecpp#2]
install the boost  with brew install boost
install the boost-python with brew install boost-python
but when I make -f Makefile incurring the problem: ld: library not found for -lboost_python

how to solve the above problem,  anyone can give me some suggestion?

**Comment by randombit** [comment]
Sorry I do not use Mac so I don't have anything to suggest. Maybe try asking on some support channel for Homebrew?

**Comment by theicfire** [comment]
I got it compiling on Mac. Here's the diff:

https://github.com/theicfire/fecpp/commit/1b5237dad352a7f0ae3835e12bda4f1cd8380156

In terms of the `boost_python` problem, the solution is to use -lboost_python27 (for me). I was hinted at this idea from this post: https://stackoverflow.com/questions/51906096/ld-library-not-found-for-lboost-python-on-macos

I found that that post was using the correct python paths, but you can check with `python2.7-config --includes --libs`

**Comment by HFTrader** [comment]
I have added a pull request to add support for cmake. it should make the integration all less painful.

**Comment by randombit** [comment]
Bad news: This library is no longer maintained.

Good news: The same functionality (zfec-compatible forward error correction with SIMD optimizations) is available in Botan with randombit/botan#2866
