### ISSUE TITLE
Regression bug: Benchmark fails tests

### ISSUE THREAD

**Issue by theicfire** [randombit/fecpp#5]
When running ./benchmark, I get lots of output that corresponds to this code:
```
            if(buf[i] != expected)
               printf("block=%d i=%d got=%02X expected=%02X\n",
                      (int)block, (int)i, buf[i], expected);

            }
```

However, if I checkout git hash eb00e8a105dbdf642234fc7543f79a7a4f46e560, it works fine!

**Comment by randombit** [comment]
Thanks for the report and bisection, I'll look at this soon.

**Comment by randombit** [comment]
Fixed now thanks again
